In [3]:
import pandas as pd
import numpy as np
import json

In [4]:
real_data=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/heart-disease/processed.cleveland.data",sep=",",header=None)

cols=["Age","sex","cp","trestbps","chol","fbs","restecg","thalach","exang","oldpeak","slope","ca","thal","num"]

real_data.columns=cols
real_data.replace("?", np.nan,inplace=True)
real_data

,Age,sex,cp,trestbps,chol,fbs,restecg,thalach,exang,oldpeak,slope,ca,thal,num
0,63.0,1.0,1.0,145.0,233.0,1.0,2.0,150.0,0.0,2.3,3.0,0.0,6.0,0
1,67.0,1.0,4.0,160.0,286.0,0.0,2.0,108.0,1.0,1.5,2.0,3.0,3.0,2
2,67.0,1.0,4.0,120.0,229.0,0.0,2.0,129.0,1.0,2.6,2.0,2.0,7.0,1
3,37.0,1.0,3.0,130.0,250.0,0.0,0.0,187.0,0.0,3.5,3.0,0.0,3.0,0
4,41.0,0.0,2.0,130.0,204.0,0.0,2.0,172.0,0.0,1.4,1.0,0.0,3.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
298,45.0,1.0,1.0,110.0,264.0,0.0,0.0,132.0,0.0,1.2,2.0,0.0,7.0,1
299,68.0,1.0,4.0,144.0,193.0,1.0,0.0,141.0,0.0,3.4,2.0,2.0,7.0,2
300,57.0,1.0,4.0,130.0,131.0,0.0,0.0,115.0,1.0,1.2,2.0,1.0,7.0,3
301,57.0,0.0,2.0,130.0,236.0,0.0,2.0,174.0,0.0,0.0,2.0,1.0,3.0,1
302,38.0,1.0,3.0,138.0,175.0,0.0,0.0,173.0,0.0,0.0,1.0,NaN,3.0,0

In [5]:
#new data
real_data2=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data",sep=",",header=None)

#https://archive.ics.uci.edu/dataset/15/breast+cancer+wisconsin+original

real_data2_cols=["id","Clump_Thickness","Uniformity_of_Cell_Size","Uniformity_of_Cell_Shape","Marginal_Adhesion","Single_Epithelial_Cell_Size","Bare_Nuclei","Bland_Chromatin","Normal_Nucleoli","Mitoses","Class"]
real_data2.columns=real_data2_cols


continuous_values2=["Clump_Thickness","Uniformity_of_Cell_Size","Uniformity_of_Cell_Shape","Marginal_Adhesion","Single_Epithelial_Cell_Size","Bare_Nuclei","Bland_Chromatin","Normal_Nucleoli","Mitoses"]

categorical_values2 = real_data2[real_data2.columns.difference(continuous_values2)].columns
real_data2.drop(columns=["id"],inplace=True)

In [6]:
real_data3=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/liver-disorders/bupa.data",sep=",",header=None)
real_data3_cols=["mcv","alkphos","sgpt","sgot","gammagt","drinks","Selector"]
real_data3.columns=real_data3_cols
#https://archive-beta.ics.uci.edu/dataset/60/liver+disorders

In [7]:
real_data4=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/thyroid-disease/new-thyroid.data",sep=",",header=None)
real_data4_cols=["Class","T3","TST","TSTRI","TSH","TMAX"]
real_data4.columns=real_data4_cols
#https://archive-beta.ics.uci.edu/dataset/60/liver+disorders

In [8]:
real_data5=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/dermatology/dermatology.data",sep=",",header=None)
real_data5_cols=["erythema",
"scaling",
"definite_borders",
"itching",
"koebner_phenomenon",
"polygonal_papules",
"follicular_papules",
"oral_mucosal_involvement",
"knee_and_elbow_involvement",
"scalp_involvement",
"family_history",
"melanin_incontinence",
"eosinophils_in_the_infiltrate",
"PNL_infiltrate",
"fibrosis_of_the_papillary_dermis",
"exocytosis",
"acanthosis",
"hyperkeratosis",
"parakeratosis",
"clubbing_of_the_rete_ridges",
"elongation_of_the_rete_ridges",
"thinning_of_the_suprapapillary_epidermis",
"spongiform_pustule",
"munro_microabcess",
"focal_hypergranulosis",
"disappearance_of_the_granular_layer",
"vacuolisation_and_damage_of_basal_layer",
"spongiosis",
"saw-tooth_appearance_of_retes",
"follicular_horn_plug",
"perifollicular_parakeratosis",
"inflammatory_monoluclear_inflitrate",
"band-like_infiltrate",
"Age_linear","class"]
real_data5.columns=real_data5_cols
#https://archive-beta.ics.uci.edu/dataset/60/liver+disorders
real_data5

,erythema,scaling,definite_borders,itching,koebner_phenomenon,polygonal_papules,follicular_papules,oral_mucosal_involvement,knee_and_elbow_involvement,scalp_involvement,...,disappearance_of_the_granular_layer,vacuolisation_and_damage_of_basal_layer,spongiosis,saw-tooth_appearance_of_retes,follicular_horn_plug,perifollicular_parakeratosis,inflammatory_monoluclear_inflitrate,band-like_infiltrate,Age_linear,class
0,2,2,0,3,0,0,0,0,1,0,...,0,0,3,0,0,0,1,0,55,2
1,3,3,3,2,1,0,0,0,1,1,...,0,0,0,0,0,0,1,0,8,1
2,2,1,2,3,1,3,0,3,0,0,...,0,2,3,2,0,0,2,3,26,3
3,2,2,2,0,0,0,0,0,3,2,...,3,0,0,0,0,0,3,0,40,1
4,2,3,2,2,2,2,0,2,0,0,...,2,3,2,3,0,0,2,3,45,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
361,2,1,1,0,1,0,0,0,0,0,...,0,0,1,0,0,0,2,0,25,4
362,3,2,1,0,1,0,0,0,0,0,...,1,0,1,0,0,0,2,0,36,4
363,3,2,2,2,3,2,0,2,0,0,...,0,3,0,3,0,0,2,3,28,3
364,2,1,3,1,2,3,0,2,0,0,...,0,2,0,1,0,0,2,3,50,3
365,3,2,2,0,0,0,0,0,3,3,...,2,0,0,0,0,0,3,0,35,1

In [9]:
real_data6=pd.read_table("https://archive.ics.uci.edu/ml/machine-learning-databases/primary-tumor/primary-tumor.data",sep=",",header=None)
real_data6_cols=["class","age","sex","histologic-type","degree-of-diffe","bone","bone-marrow","lung","pleura","peritoneum","liver","brain","skin","neck","supraclavicular","axillar","mediastinum","abdominal"]

real_data6.columns=real_data6_cols

#https://archive.ics.uci.edu/ml/machine-learning-databases/primary-tumor/
real_data6

,class,age,sex,histologic-type,degree-of-diffe,bone,bone-marrow,lung,pleura,peritoneum,liver,brain,skin,neck,supraclavicular,axillar,mediastinum,abdominal
0,1,1,1,?,3,2,2,1,2,2,2,2,2,2,2,2,2,2
1,1,1,1,?,3,2,2,2,2,2,1,2,2,2,1,2,1,2
2,1,1,2,2,3,1,2,2,2,2,2,2,2,2,2,2,1,2
3,1,1,2,?,3,1,2,1,1,2,2,2,2,2,2,2,1,2
4,1,1,2,?,3,1,2,1,1,2,2,2,2,2,2,2,1,2
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
334,22,2,2,2,?,2,2,2,2,2,2,2,2,2,2,1,2,2
335,22,2,2,2,?,2,2,2,2,2,2,2,2,2,2,1,2,2
336,22,2,2,?,?,1,2,2,2,2,2,2,2,2,1,1,2,2
337,22,3,2,2,2,2,2,2,2,2,2,2,2,1,1,1,2,2
338,22,3,2,2,2,2,2,2,2,2,2,2,2,2,1,1,2,2

In [15]:

#heart disease \cite{misc_heart_disease_45}, 
# thyroid disease \cite{misc_thyroid_disease_102},
#  liver disorders \cite{misc_liver_disorders_60},
#  breast cancer \cite{misc_breast_cancer_wisconsin_(diagnostic)_17} 
# and the primary tumor dataset \cite{misc_primary_tumor_83}.
def calculate_statistics(df, df_name):
    summary = []

    for col in df.columns:
        col_data = df[col]
        if pd.api.types.is_numeric_dtype(col_data):
            # Continuous data
            mean_val = round(col_data.mean(),1)
            std_dev = round(col_data.std(),1)
            null_percentage = round(col_data.isnull().mean() * 100,1)
            summary.append([df_name, col, f"{mean_val} ({std_dev})", null_percentage])
        else:
            # Categorical data
            mode_val = col_data.mode().iloc[0] if not col_data.mode().empty else np.nan
            num_categories = col_data.nunique()
            null_percentage = round(col_data.isnull().mean() * 100,1)
            summary.append([df_name, col, f"{mode_val} [{num_categories}]", null_percentage])

    return pd.DataFrame(summary, columns=["Dataset", "Column", "Statistic", "% Nulls"])

# Assuming you have 5 DataFrames named df1, df2, df3, df4, and df5
df1_summary = calculate_statistics(real_data, "heart")
df2_summary = calculate_statistics(real_data2, "breast")
df3_summary = calculate_statistics(real_data3, "liver")
df4_summary = calculate_statistics(real_data4, "thyroid")
df5_summary = calculate_statistics(real_data6, "tumor")

# Combine all summaries into one DataFrame
final_summary = pd.concat([df1_summary, df2_summary, df3_summary, df4_summary, df5_summary], ignore_index=True)

# Display the final summary dataframe
final_summary

   DataFrame                       Column     Statistic  % Nulls
0      heart                          Age    54.4 (9.0)      0.0
1      heart                          sex     0.7 (0.5)      0.0
2      heart                           cp     3.2 (1.0)      0.0
3      heart                     trestbps  131.7 (17.6)      0.0
4      heart                         chol  246.7 (51.8)      0.0
5      heart                          fbs     0.1 (0.4)      0.0
6      heart                      restecg     1.0 (1.0)      0.0
7      heart                      thalach  149.6 (22.9)      0.0
8      heart                        exang     0.3 (0.5)      0.0
9      heart                      oldpeak     1.0 (1.2)      0.0
10     heart                        slope     1.6 (0.6)      0.0
11     heart                           ca       0.0 [4]      1.3
12     heart                         thal       3.0 [3]      0.7
13     heart                          num     0.9 (1.2)      0.0
14    breast              Clump_Thickness     4.4 (2.8)      0.0
15    breast      Uniformity_of_Cell_Size     3.1 (3.1)      0.0
16    breast     Uniformity_of_Cell_Shape     3.2 (3.0)      0.0
17    breast            Marginal_Adhesion     2.8 (2.9)      0.0
18    breast  Single_Epithelial_Cell_Size     3.2 (2.2)      0.0
19    breast                  Bare_Nuclei        1 [11]      0.0
20    breast              Bland_Chromatin     3.4 (2.4)      0.0
21    breast              Normal_Nucleoli     2.9 (3.1)      0.0
22    breast                      Mitoses     1.6 (1.7)      0.0
23    breast                        Class     2.7 (1.0)      0.0
24     liver                          mcv    90.2 (4.4)      0.0
25     liver                      alkphos   69.9 (18.3)      0.0
26     liver                         sgpt   30.4 (19.5)      0.0
27     liver                         sgot   24.6 (10.1)      0.0
28     liver                      gammagt   38.3 (39.3)      0.0
29     liver                       drinks     3.5 (3.3)      0.0
30     liver                     Selector     1.6 (0.5)      0.0
31   thyroid                        Class     1.4 (0.7)      0.0
32   thyroid                           T3  109.6 (13.1)      0.0
33   thyroid                          TST     9.8 (4.7)      0.0
34   thyroid                        TSTRI     2.1 (1.4)      0.0
35   thyroid                          TSH     2.9 (6.1)      0.0
36   thyroid                         TMAX     4.2 (8.1)      0.0
37     tumor                        class     8.7 (7.1)      0.0
38     tumor                          age     2.2 (0.6)      0.0
39     tumor                          sex         2 [3]      0.0
40     tumor              histologic-type         2 [4]      0.0
41     tumor              degree-of-diffe         ? [4]      0.0
42     tumor                         bone     1.7 (0.4)      0.0
43     tumor                  bone-marrow     2.0 (0.1)      0.0
44     tumor                         lung     1.8 (0.4)      0.0
45     tumor                       pleura     1.8 (0.4)      0.0
46     tumor                   peritoneum     1.7 (0.4)      0.0
47     tumor                        liver     1.7 (0.5)      0.0
48     tumor                        brain     1.9 (0.2)      0.0
49     tumor                         skin         2 [3]      0.0
50     tumor                         neck     1.9 (0.3)      0.0
51     tumor              supraclavicular     1.8 (0.4)      0.0
52     tumor                      axillar         2 [3]      0.0
53     tumor                  mediastinum     1.7 (0.4)      0.0
54     tumor                    abdominal     1.7 (0.5)      0.0

In [16]:
with open("output.tex", "w") as file:
        file.write(final_summary.to_latex(index=False,float_format="{:.1f}".format))

In [17]:
final_summary.to_csv("output.csv")